import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Sidebar from '@/features/sidebar/layout/sidebar';
import { ThemeScript } from '@/features/provider/theme-script';
import QueryClientProviders from '@/features/provider/queryclient-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-dvh`}
      >
        <ThemeScript />
        <QueryClientProviders>
          <div className="flex grow">
            <Sidebar />
            <main className="flex grow bg-white dark:bg-black">{children}</main>
          </div>
        </QueryClientProviders>
        {/** Header자리 */}
      </body>
    </html>
  );
}
